# INSTALAR PAQUETES
# run: apt-get install nginx curl
name: Test

on: [push]

jobs:
    test-build:
        runs-on: ubuntu-latest

# Situarnos en el repo
        steps:
          - name: Checkout
            uses: actions/checkout@v2
# Para dar permisos de ejecución al script.sh, para posteriormente ejecutar el script
          - name: ls
            run: |
              chmod +x script.sh
              ./script.sh

# Utilizar acción local
          - name: ls action
            uses: ./.github/actions/my-action